flush: scripts/flush.sh
	./scripts/flush.sh

fresh: scripts/fresh.sh
	./scripts/fresh.sh

stop: scripts/stop.sh
	./scripts/stop.sh

start: scripts/start.sh
	./scripts/start.sh

restart: scripts/restart.sh
	./scripts/restart.sh

FORCE:
